[pytest]
# 添加默认参数：-v（详细输出），-s（显示打印信息），--alluredir（生成Allure报告）
# addopts = -v -s --alluredir=./allure-results
addopts = -v -s


# 测试文件目录
testpaths = ./tests

# 自定义测试文件、类、函数匹配规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 注册自定义标签（防止运行警告）
markers =
    smoke: smoke tests
    regression: regression tests
