from typing import Optional

class MyError(Exception): ...
class ChildErrorA(MyError): ...
class ChildErrorB(MyError): ...
class ChildErrorC(MyError): ...

class Student:
    name: str
    age: int

    def __init__(self, name: str, age: int) -> Student:
        """描述一下这个类是做什么的

        Args:
            name (str): 姓名
            age (int): 年龄

        Returns:
            Student: 返回对象
        """
        ...
    def set_large_age(self, ages: list[int]): ...
    def raise_exception(self, number: Optional[int]) -> str: ...
    def set_other_age(self, stu: Student): ...

def list_to_dic(names: list[str]) -> dict[int, str]: ...
def dic_to_list(input_dic: dict[str, str]) -> list[str]: ...
def many_args(num: int, *args, **kwargs) -> str: ...
def parallel_sum_of_squares(num: int) -> int: ...
def student_info(stu: Student) -> str: ...
def student_set_age(stu: Student, age: int): ...
